import type { Metadata } from 'next';
import './globals.css';
import MenuUserMobile from '@/components/Navbar/MenuUserMobile';
import Footer from '@/components/elements/Footer';

export const metadata: Metadata = {
  title: 'invitation 6',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <div className="md:w-[500px] border border-gray-100 shadow-sm border-b-0 bg-white mx-auto space-y-20 min-h-screen">
            {children}
            {/* Footer */}
            <Footer />
            {/* nav */}
            <MenuUserMobile />
            {/* nav end */}
          </div>
        </main>
      </body>
    </html>
  );
}
